/**
 * Tailscale API Routes
 * Manage Tailscale integration, status, and configuration
 */
const express = require('express');
const database = require('../../utils/database');
const tailscale = require('../../utils/tailscale');
const authenticate = require('../../middleware/auth');
const logger = require('../../utils/logger');

const router = express.Router();

// All routes require authentication
router.use(authenticate);

// Get Tailscale status
router.get('/status', (req, res) => {
  try {
    const status = tailscale.getStatus();
    const settings = {
      enabled: database.getSetting('tailscale_enabled') === 'true',
      hasApiKey: !!database.getSetting('tailscale_api_key'),
      tailnet: database.getSetting('tailscale_tailnet') || '',
    };

    res.json({
      success: true,
      tailscale: { ...status, ...settings },
    });
  } catch (error) {
    logger.error('Error getting Tailscale status:', error);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

// Update Tailscale settings
router.post('/settings', async (req, res) => {
  try {
    const { enabled, apiKey, tailnet, hostname } = req.body;

    if (enabled !== undefined) {
      database.setSetting('tailscale_enabled', enabled ? 'true' : 'false');
    }
    if (apiKey !== undefined) {
      database.setSetting('tailscale_api_key', apiKey);
    }
    if (tailnet !== undefined) {
      database.setSetting('tailscale_tailnet', tailnet);
    }
    if (hostname !== undefined) {
      database.setSetting('tailscale_hostname', hostname);
    }

    res.json({ success: true, message: 'Tailscale settings updated' });
  } catch (error) {
    logger.error('Error updating Tailscale settings:', error);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

// Start Tailscale connection
router.post('/connect', async (req, res) => {
  try {
    const { authKey, hostname } = req.body;

    const result = await tailscale.start({
      authKey,
      hostname: hostname || database.getSetting('tailscale_hostname') || 'nexus-server',
      acceptRoutes: true,
    });

    res.json({ success: true, message: 'Tailscale connected', ...result });
  } catch (error) {
    logger.error('Error connecting Tailscale:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

// Stop Tailscale connection
router.post('/disconnect', (req, res) => {
  try {
    tailscale.stop();
    res.json({ success: true, message: 'Tailscale disconnected' });
  } catch (error) {
    logger.error('Error disconnecting Tailscale:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

// List Tailscale devices via API
router.get('/devices', async (req, res) => {
  try {
    const apiKey = database.getSetting('tailscale_api_key');
    const tailnet = database.getSetting('tailscale_tailnet');

    if (!apiKey || !tailnet) {
      return res.status(400).json({
        success: false,
        error: 'Tailscale API key and tailnet required. Configure in settings.',
      });
    }

    const devices = await tailscale.listDevices(apiKey, tailnet);
    res.json({ success: true, devices });
  } catch (error) {
    logger.error('Error listing Tailscale devices:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

// Generate pre-auth key
router.post('/auth-key', async (req, res) => {
  try {
    const apiKey = database.getSetting('tailscale_api_key');
    const tailnet = database.getSetting('tailscale_tailnet');
    const { reusable, ephemeral, tags, expirySeconds } = req.body;

    if (!apiKey || !tailnet) {
      return res.status(400).json({
        success: false,
        error: 'Tailscale API key and tailnet required',
      });
    }

    const key = await tailscale.generateAuthKey(apiKey, tailnet, {
      reusable,
      ephemeral,
      tags,
      expirySeconds,
      description: 'Generated by Nexus for node enrollment',
    });

    res.json({ success: true, key });
  } catch (error) {
    logger.error('Error generating Tailscale auth key:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

// Get Tailscale IP for Nexus URL
router.get('/nexus-url', (req, res) => {
  try {
    const url = tailscale.getNexusUrl();
    if (!url) {
      return res.json({ success: false, error: 'Tailscale IP not available' });
    }
    res.json({ success: true, url });
  } catch (error) {
    logger.error('Error getting Tailscale Nexus URL:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

module.exports = router;
